### ISSUE TITLE
Determine correct propagation behavior for ambiguous cases

### ISSUE THREAD

**Issue by mlevesquedion** [google/go-flow-levee#188]
PR #178 added explicit handling for each node type.

For most node types, it is obvious what the correct behavior is, e.g. when doing a `MapUpdate`, we shouldn't be traversing to the `Key` or the `Value`, only the `Map`.

For other node types, the correct behavior is not obvious.

Here are the cases that need further investigation, and likely, more tests: 
- [x] `Field`: addressed by #201.
- [x] `Store`: addressed by #199.
- [x] `Select` and `SelectCase`: addressed by #235.
- [x] `MakeInterface`: see #209.
- [x] `TypeAssert`: see #210.
- [x] `Lookup` and `Next`.
- [x] `Slice`: see #236.
- [x] `UnOp`: see below.

**Comment by mlevesquedion** [comment]
I have investigate `ssa.UnOp` instructions and I believe the best we can do for now is to keep visiting the `Operands`. Under the current approach I don't see a straightforward way to handle the following cases without visiting the `Operands`. I think this would be easy to handle with an interpretation-based approach, however.

First, consider this case:
```go
func TestArrOfPointersIsTainted(s core.Source, arr [1]*string) {
	colocateArrOfPointers(s, arr)
	core.Sink(arr) // want "a source has reached a sink"
}
```

The relevant portion of the SSA graph is:

![image](https://user-images.githubusercontent.com/28677454/102559726-8f698600-409e-11eb-942e-f5766e88fdf0.png)

We need to traverse to the `Operand` (in this case, `t1`) when coming from the `Call`, because otherwise we can't get to the `sink`.

Also consider this case:
```go
func TestSanitizedSourceDoesNotTriggerFindingWhenTypeAsserted(s *core.Source) {
	sanitized := core.Sanitize(s)[0].(*core.Source)
	core.Sinkf("Sanitized %v", sanitized)
}
```

The relevant portion of the SSA graph is:

![image](https://user-images.githubusercontent.com/28677454/102559814-c049bb00-409e-11eb-8015-ea8a77bdda60.png)

We need to traverse to the `Operand` in order to find the `Sanitizer`. Otherwise, the `Source` produced by the `TypeAssert` is considered unsanitized. This could be seen as a failure of the `isProducedBySanitizer` function. I have opened an issue here: #237.
